### PR TITLE
Update recipe for 0.4.0 release

### PR DESCRIPTION
**Pull request by jhamrick**

### CODE REVIEW

**Comment by jhamrick** [comment]
Hmm, tests are failing with `pkg_resources.DistributionNotFound: The 'jupyter' distribution was not found and is required by nbgrader` on the following test:

```
    def test_check_version(self, capfd):
        """Is the version the same regardless of how we run nbgrader?"""
        out1 = '\n'.join(
>           run_command(["nbgrader", "--version"]).splitlines()[-3:]
        ).strip()
```

I have verified it is installing jupyter, so I am not sure what could be causing this.

**Comment by jhamrick** [comment]
Forcing it to use `sys.executable` seems to fix it, I think.

**Comment by jhamrick** [comment]
This will be fixed officially by https://github.com/jupyter/nbgrader/pull/695 but for now I'll leave it as a patch.

**Comment by lgpage** [comment]
@jhamrick need to reset the build number to 0 and we may be able to re-render and include Python3.6

**Comment by jhamrick** [comment]
Meh, `pytest-rerunfailures` isn't available on conda. Does that mean we have to package it for conda, or is there a way to tell it to install from pip?

**Comment by jhamrick** [comment]
Some googling suggests it would require building a separate conda package. There are a few existing versions of `pytest-rerunfailures` in other channels:

```
$ anaconda search -t conda pytest-rerunfailures
Using Anaconda Cloud api site https://api.anaconda.org
Run 'anaconda show <USER/PACKAGE>' to get more details:
Packages:
     Name                      |  Version | Package Types   | Platforms
     ------------------------- |   ------ | --------------- | ---------------
     auto/pytest-rerunfailures |     0.03 | conda           | linux-64
                                          : https://github.com/klrmn/pytest-rerunfailures
     birdsarah/pytest-rerunfailures |    1.0.1 | conda           | osx-64
                                          : pytest plugin to re-run tests to eliminate flaky failures
     bokeh/pytest-rerunfailures |    1.0.1 | conda           | linux-64, win-32, win-64, linux-32, osx-64
                                          : pytest plugin to re-run tests to eliminate flaky failures
```

**Comment by lgpage** [comment]
I think the best may be to skip the ``nbextension`` tests for now and try fix them separately?

Also can you re-render with conda-smithy 2.0.1?

**Comment by jhamrick** [comment]
Yes, maybe that's best for now.

I will re-render it with conda-smithy.

**Comment by lgpage** [comment]
LGTM, can I go ahead and merge?

**Comment by jhamrick** [comment]
Oh good! I am glad all the tests finally passed. Yes, ready to merge 😄

**Pull request merged**
